---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Display all facts
      debug:
        var: ansible_facts
    - name: install apache2 webserve:r
      apt:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"
    - name: install git on the node side
      apt:
        name: git
        state: present
      when: ansible_os_family=="Debian"
    - name: start webserver on the node side
      service:
        name: apache2
        state: started
      when: ansible_os_family=="Debian"

