---
- hosts: all
  become: yes
  tasks:
    - name: install apache2 webserver
      apt:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"
    - name: install git on the node side
      apt:
        name: git
        state: present
      when: ansible_os_family=="Debian"
    - name: start webserver on the node side
      service:
        name: apache2
        state: start
      when: ansible_os_family=="Debian"

