---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Display the IP address
      debug:
        var: ansible_facts['default_ipv4']['address']
    - name: Display hostname
      debug:
        msg: "The hostname of this system is {{ ansible_facts['hostname'] }}"
    - name: Display OS type
      debug:
        msg: "This system is running {{ ansible_facts['os_family'] }} OS"
    - name: install apache2 webserver
      apt:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"
    - name: install git on the node side
      apt:
        name: git
        state: present
      when: ansible_os_family=="Debian"
    - name: start webserver on the node side
      service:
        name: apache2
        state: started
      when: ansible_os_family=="Debian"
    - name: start webserver on the RedHat node side
      dnf:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"

    - name: start webserver on the RedHat node side
      service:
        name: httpd
        state: started
      when: ansible_os_family=="RedHat"

